Rename Adventure arguments
JorelAli/CommandAPI pull request #474
Opened 2023-07-24 20:57 UTC by DerEchtePilz

This essentially makes these changes to make arguments that deal with the same Minecraft argument type have identical names:

- Spigot-related argument changes:

```patch
- dev.jorel.commandapi.arguments.ChatArgument
- dev.jorel.commandapi.arguments.ChatColorArgument
- dev.jorel.commandapi.arguments.ChatComponentArgument

+ dev.jorel.commandapi.arguments.spigot.ChatArgument
+ dev.jorel.commandapi.arguments.spigot.ChatColorArgument
+ dev.jorel.commandapi.arguments.spigot.ChatComponentArgument
```

- Adventure-related argument changes:

```patch
- dev.jorel.commandapi.arguments.AdventureChatArgument
- dev.jorel.commandapi.arguments.AdventureChatColorArgument
- dev.jorel.commandapi.arguments.AdventureChatComponentArgument

+ dev.jorel.commandapi.arguments.adventure.ChatArgument
+ dev.jorel.commandapi.arguments.adventure.ChatColorArgument
+ dev.jorel.commandapi.arguments.adventure.ChatComponentArgument
```

2023-07-24 20:59 UTC, DerEchtePilz reviewed
Yes, I did review my own PR :D
Basically, I just want to remind myself to actually make these changes when the time has come

2023-07-24 20:59 UTC, DerEchtePilz commented on README.md
> +        </tr>
Probably fill this with more content.

2023-07-24 20:59 UTC, DerEchtePilz commented on README.md
> +                    <li>https://github.com/JorelAli/CommandAPI/issues/469 Adds <code>ChatColorArgument</code> for Adventure</li>
Change this back to `AdventureChatColorArgument`

2023-07-24 20:59 UTC, DerEchtePilz commented on docssrc/src/upgrading.md
> +## From 9.?.? to 10.0.0
Make this `9.?.?` say the correct version when this is ready to be merged

2023-07-25 00:35 UTC, JorelAli commented
The one mildly annoying thing with this PR is the developer experience. Developers now need to ensure that they import the "right one". There are no compile-time checks that will catch the case if a developer accidentally uses the wrong argument. (I'm only saying "mildly annoying", because the CommandAPI does have cases where it has classes which have the same name as other cases, such as NamespacedKey)

Not something worth rejecting the PR, just something to be aware of (of course, the fix for this is trivial on the developers point of view, and runtime errors will occur which should be detected during developer testing, so it's "easily identifiable"). We'll have to ensure that the documentation fully covers this to ensure that users don't mix them up (we should now have an intermediary "chat arguments" page, we can probably put a note about this there so developers know which package to import)

2023-07-25 14:23 UTC, willkroboth commented
> The one mildly annoying thing with this PR is the developer experience. Developers now need to ensure that they import the "right one". There are no compile-time checks that will catch the case if a developer accidentally uses the wrong argument. (I'm only saying "mildly annoying", because the CommandAPI does have cases where it has classes which have the same name as other cases, such as NamespacedKey)

Yeah, it is a little confusing. Similar things happened to me when I accidentally import `java.awt.List` instead of `java.util.List`.

Maybe this could be similar to those `NamespacedKey` examples. There could be a `ChatArgument`/`ChatColorArgument`... class for the Spigot case and `ChatArgument.Adventure`/`ChatColorArgument.Adventure`... for Adventure. Or, since Spigot doesn't have to be the 'default', there could be `ChatArgument.Spigot`/`ChatColorArgument.Spigot`... instead.

Going that way would pretty much be no change at all though. If it's not a big change, it's probably not going to solve the problem you are trying to solve.

> Not something worth rejecting the PR, just something to be aware of (of course, the fix for this is trivial on the developers point of view, and runtime errors will occur which should be detected during developer testing, so it's "easily identifiable"). We'll have to ensure that the documentation fully covers this to ensure that users don't mix them up (we should now have an intermediary "chat arguments" page, we can probably put a note about this there so developers know which package to import)

As Skepter said, documentation could probably help with any possible confusion with the way it is right now.

2023-09-24 20:28 UTC, DerEchtePilz commented
Alright, I guess, this should be done.

Once again, the only thing I am really not sure about is documentation. In this case, the `chatpreview.md` page as that refers to different platform implementation several times. I personally think I found a good compromise between only naming the class name and mentioning the platform every time too.

So yeah, a code review would be appreciated for the whole PR :D

2023-09-25 14:35 UTC, willkroboth requested changes
Just a few typos and small details I noticed. Otherwise, everything makes sense.

I'm still not sure what problem this is trying to solve. I've never used the chat arguments though, so I'm not sure how developers want to use them. One challenge I see with the setup here is providing support for Spigot and Adventure. Right now, if you want to use both `ChatArgument`s in the same file, you need to use the fully qualified name (eg. `dev.jorel.commandapi.arguments.spigot.ChatArgument`) for at least one of them, which doesn't seem convenient. I don't know if anyone would want to do that, but this is currently happening in the `ChatArgumentTests` files.

I think placing the arguments as static classes like `ChatArgument.Spigot` and `ChatArgument.Adventure` fits better with existing Arguments (Eg. `SoundArgument` and `SoundArgument.NamespacedKey` both use the `minecraft:resource_location` Brigadier argument). I don't know though. The best solution probably depends on the problem that this is trying to solve.

If we think different packages is the best solution,  this PR looks good to me :+1:.

2023-09-25 14:35 UTC, willkroboth commented on docssrc/src/chatpreview.md
> +The method `withPreview(PreviewableFunction preview)` lets you generate a preview to send to the client. This method takes in the `PreviewableFunction` functional interface, which is a function that
Just a tiny typo, it looks like there's a space missing. 
```suggestion
The method `withPreview(PreviewableFunction preview)` lets you generate a preview to send to the client. This method takes in the `PreviewableFunction` functional interface, which is a function that takes in a `PreviewInfo` and returns either a `BaseComponent[]` (for the Spigot-based `ChatArgument`) or a `Component` (for the Adventure-based `ChatArgument`):
```
<img width="747" alt="Screen Shot 2023-09-25 at 10 10 27 AM" src="https://github.com/JorelAli/CommandAPI/assets/46540330/a7d0f8ab-d0ff-46f1-b76f-1423a3d63bc4">

2023-09-25 14:35 UTC, willkroboth commented on docssrc/src/chatpreview.md
> +`parsedInput()` is similar to `input()`, except it has been parsed by the CommandAPI's argument parser. This is a representation of what the argument in the executor would look like. For the Spigot-b
Just a tiny typo, it looks like there's a space missing.
```suggestion
`parsedInput()` is similar to `input()`, except it has been parsed by the CommandAPI's argument parser. This is a representation of what the argument in the executor would look like. For the Spigot-based `ChatArgument` the return type is `BaseComponent[]`, and for the Adventure-based `ChatArgument` the return type is `Component`.
```
<img width="762" alt="Screen Shot 2023-09-25 at 10 14 12 AM" src="https://github.com/JorelAli/CommandAPI/assets/46540330/c303343f-d544-43c0-b322-fa6438bb6ebd">

2023-09-25 14:53 UTC, DerEchtePilz commented
> Just a few typos and small details I noticed. Otherwise, everything makes sense.
> 
> I'm still not sure what problem this is trying to solve. I've never used the chat arguments though, so I'm not sure how developers want to use them. One challenge I see with the setup here is providing support for Spigot and Adventure. Right now, if you want to use both `ChatArgument`s in the same file, you need to use the fully qualified name (eg. `dev.jorel.commandapi.arguments.spigot.ChatArgument`) for at least one of them, which doesn't seem convenient. I don't know if anyone would want to do that, but this is currently happening in the `ChatArgumentTests` files.
> 
> I think placing the arguments as static classes like `ChatArgument.Spigot` and `ChatArgument.Adventure` fits better with existing Arguments (Eg. `SoundArgument` and `SoundArgument.NamespacedKey` both use the `minecraft:resource_location` Brigadier argument). I don't know though. The best solution probably depends on the problem that this is trying to solve.
> 
> If we think different packages is the best solution, this PR looks good to me 👍.

First, thanks for the review!
I am not really solving a problem with this since the arguments work fine the way they currently are, I just thought it would be nice if arguments that provide essentially the same functionality had the same name. [My initial discord message](https://discord.com/channels/745416925924032523/745419648970784821/1133075142340247632)
Of course, when I originally had the idea I didn't think about the case where someone would like to use both arguments in the same class (why would someone even want to do this, if you got Adventure, use Adventure).
Given that 10.0.0 isn't quite releasing any time soon, we still can discuss this package vs. inner class thing, I personally would continue to use this but using inner class would be fine as well.

2024-01-19 15:11 UTC, DerEchtePilz commented
Superseded by #517

2024-01-19 15:11 UTC, closed without merging